name: unittest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install coverage
    - name: Add dependencies about external libraries
      run: |
        pip install pyqt5
        sudo apt-get install python3-pyqt5
    - name: Unittest the code with coverage
      run: |
        xvfb-run `which coverage` run --source=qiwis -m unittest discover -b
        xvfb-run `which coverage` report
